### ISSUE TITLE
Update openPGP.js

### ISSUE THREAD

**Issue by Mikiya83** [Rafficer/WebGPG#1]
Hi, 
Thanks for your little project :)
Can you update it to the last lib version of OpenPGP.js ? I tried with v3.0.4 in local and i can't see any problems so it could be cool to have it on the public version.

**Comment by Rafficer** [comment]
Will do :)

I'm amazed someone stumbled upon this... I should put some more time in it :P

**Comment by Rafficer** [comment]
Thanks again for #2.

https://gpg.ncrypt.sh will automatically update within the next 6h, if you don't host it yourself :)
